config/routes.rb
Rails.application.routes.draw do
  get 'buy/index'
    namespace 'v1' do
      resources :api_tables
    end
  get 'orders/index'
  get 'orders_history/index'
  devise_for :users
  get 'home/index'
  get 'home/index'
  root to: "home#index"
  resources :vegetables
  resources :categories
  resources :maps
  resources :addresses
  resources :orders
  resources :order_histories
  resources :user_profiles
  resources :cart_items
  resources :buy
  post '/add_to_cart', to: 'vegetables#add_to_cart'
  post '/create', to: 'orders#create'
  post '/incr_quantity', to: 'vegetables#incr_quantity'
  post '/decr_quantity', to: 'vegetables#decr_quantity'
  get '/send_mail' => 'orders#send_mail'
  # resources :charges, only: [:new, :create]


end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/api_table.rb
class ApiTable < ApplicationRecord
	validates :name , presence: true
	validates :email , presence: true
	validates :password , presence: true
	validates :auth , presence: true
	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
   
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
	has_many :cart_items
	belongs_to :user
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	has_many :vegetables
	belongs_to :cart
	has_many_attached :vegetable_img
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :vegetables
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :user
	belongs_to :vegetable

   
end

app/models/order_history.rb
class OrderHistory < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  devise :database_authenticatable, :validatable, password_length: 6..128
  has_one_attached :user_img
  has_many :addresses
  has_one :cart
  has_many :cart_items
  has_many :orders

end

app/models/vegetable.rb
class Vegetable < ApplicationRecord
	belongs_to :cart_item
	has_many :orders
	has_one_attached :vegetable_img
	def self.search_by(search_term)
	where("LOWER(name) LIKE :search_term ",search_term: "%#{search_term.downcase}%")
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

def index
    @vegetable = Vegetable.all.paginate(page: params[:page], per_page: 6)
  if params[:search]
    @search_term = params[:search]
    @vegetable = Vegetable.search_by(@search_term).paginate(page: params[:page], per_page: 6)
  end
end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController

	def index
	end
end

app/helpers/address_helper.rb
module AddressHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/helpers/vegetables_helper.rb
module VegetablesHelper
end

app/views/home/_footer.html.erb
<style type="text/css">
	.und_line
{
	text-decoration:none;
}
</style>
<!-- Remove the container if you want to extend the Footer to full width. -->
<div class="container-fluid my-5">

  <!-- Footer -->
  <footer
          class="text-center text-lg-start text-white"
          style="background-color: #1c2331"
          >
    <!-- Section: Social media -->
    <section
             class="d-flex justify-content-between p-4"
             style="background-color: #6351ce"
             >
      <!-- Left -->
      <div class="me-5">
        <span>Get connected with us on social networks:</span>
      </div>
      <!-- Left -->

      <!-- Right -->
      <div>
        <a href="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.3
" class="text-white me-4">
          <i class="fa fa-facebook"></i>
        </a>
        <a href="https://platform.twitter.com/" class="text-white me-4">
          <i class="fa fa-twitter"></i>
        </a>
        <a href="https://apis.google.com" class="text-white me-4">
          <i class="fa fa-google"></i>
        </a>
        <a href="" class="text-white me-4">
          <i class="fa fa-instagram"></i>
        </a>
        <a href="https://www.linkedin.com/" class="text-white me-4">
          <i class="fa fa-linkedin"></i>
        </a>
        <a href="https://github.com/" class="text-white me-4">
          <i class="fa fa-github"></i>
        </a>
      </div>
      <!-- Right -->
    </section>
    <!-- Section: Social media -->

    <!-- Section: Links  -->
    <section class="">
      <div class="container text-center text-md-start mt-5">
        <!-- Grid row -->
        <div class="row mt-3">
          <!-- Grid column -->
          <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
            <!-- Content -->
            <h6 class="text-uppercase fw-bold">Company name</h6>
            <hr
                class="mb-4 mt-0 d-inline-block mx-auto"
                style="width: 60px; background-color: #7c4dff; height: 2px"
                />
            <p>
              People vegetable gardense.
            </p>
          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold">Products</h6>
            <hr
                class="mb-4 mt-0 d-inline-block mx-auto"
                style="width: 60px; background-color: #7c4dff; height: 2px"
                />
            <p>
              <a href="#!" class="text-white und_line">Vegetable</a>
            </p>
            <p>
              <a href="#!" class="text-white und_line">Grocery</a>
            </p>
            <p>
              <a href="#!" class="text-white und_line">Fruits</a>
            </p>
            <!-- <p>
              <a href="#!" class="text-white">Bootstrap Angular</a>
            </p> -->
          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold">Useful links</h6>
            <hr
                class="mb-4 mt-0 d-inline-block mx-auto"
                style="width: 60px; background-color: #7c4dff; height: 2px"
                />
           <p>
           <span class="fa fa-user"> <%= link_to 'User Profile', user_profiles_path,style:"color:white;text-decoration:none;" %></span>
            </p>
            <p>
               <span class="fa fa-refresh"> <%= link_to 'Edit Profile', edit_user_registration_path,style:"color:white;text-decoration:none;" %></span>
            </p>
            <p>
             <span class="fa fa-home"> <%= link_to 'Home',home_index_path,style:"color:white;text-decoration:none;" %></span>
            </p>
          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold">Contact</h6>
            <hr
                class="mb-4 mt-0 d-inline-block mx-auto"
                style="width: 60px; background-color: #7c4dff; height: 2px"
                />
            <p><i class="fas fa-home mr-3"></i> Noida Uttar Pradesh <%#=@user.address%></p>
            <p><i class="fas fa-envelope mr-3"></i> admin@gmail.com<%#=@user.email%></p>
            <p><i class="fas fa-phone mr-3"></i> + 77896875756 <%#=@user.mobno%></p>
            <p><i class="fas fa-print mr-3"></i> + 01 234 567 89</p>
          </div>
          <!-- Grid column -->
        </div>
        <!-- Grid row -->
      </div>
    </section>
    <!-- Section: Links  -->

    <!-- Copyright -->
    <div
         class="text-center p-3"
         style="background-color: rgba(0, 0, 0, 0.2)"
         >
      © 2020 Copyright:
      <a class="text-white" href="https://mdbootstrap.com/"
         >Ruby On Rails </a
        >
    </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer -->

</div>
<!-- End of .container -->

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
<div class="container-fluid">

<%= link_to home_index_path do %>
   <%= image_tag "logo2.jpg",style:"height:40px;width:200px;border-radius:5px;" %>
<% end %>

<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
<span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarSupportedContent">
<ul class="navbar-nav me-auto mb-2 mb-lg-0">

<% if user_signed_in? %>
<% if current_user.role =='admin'%>
<!-- admin search input box -->
<div style="margin-top:4px;">
<%= form_for "",url:  home_index_path , role: "search" , method: :get do%>
<%= text_field_tag :search, @search_term , placeholder: "search",style:"border-radius:5px;height:35px;margin-left:7px;"%>
<%end%>
</div>
<!-- admin dropsown list -->
<div class="dropdown" style="margin-left:500px;">
<button class="btn btn-info dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
  Select List
</button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
    <li class="nav-item">
    <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link',style:"color:black;" %>
    </li>
    <li class="nav-item">
    <%= link_to 'Edit Profile', edit_user_registration_path,class: 'nav-link',style:"color:black;" %>
    </li>
    <li class="nav-item">
    <%= link_to 'add vegetable', new_vegetable_path,class: 'nav-link',style:"color:black;" %>
    </li>
    <li class="nav-item">
    <%= link_to 'vegetable list',home_index_path,class: 'nav-link',style:"color:black;" %>
    </li>
    <li class="nav-item">
    <%= link_to 'add category',new_category_path,class: 'nav-link',style:"color:black;" %>
    </li>
    <li class="nav-item">
    <%= link_to 'All category',categories_path,class: 'nav-link',style:"color:black;" %>
    </li>
  </ul>
</div>
<!-- end admin dropdown-->
<% else %>
<!-- <form class="d-flex">
<input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
<button class="btn btn-outline-success" type="submit">Search</button>
</form> -->
<!--user search box-->
<div style="margin-top:2px;margin-left: 10px;">
  <%= form_for "",url:  home_index_path , role: "search" , method: :get do%>
  <%= text_field_tag :search, @search_term , placeholder: "search",style:"border-radius:5px;height:35px;padding-left:7px;"%>
  <%end%>
</div>
<!--end user search box-->
<!--user dropdown -->
<div class="dropdown" style="margin-left:400px; ">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
   Select List
  </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
      <li class="nav-item">
        <%= link_to 'User Profile', user_profiles_path,class: 'nav-link',style:"color:black;" %>
    </li>
    <li class="nav-item">
        <%= link_to 'Edit Profile', edit_user_registration_path,class: 'nav-link',style:"color:black;" %>
    </li>
    <li class="nav-item">
        <%= link_to 'All vegetable list',home_index_path,class: 'nav-link',style:"color:black;" %>
    </li>
     <li class="nav-item">
        <%= link_to 'Add address',new_address_path,class: 'nav-link',style:"color:black;" %>
    </li>
         <li class="nav-item">
        <%= link_to 'Address list',addresses_path,class: 'nav-link',style:"color:black;" %>
    </li>
      </li>
         <li class="nav-item">
        <%= link_to 'cart list',cart_items_path,class: 'nav-link',style:"color:black;" %>
    </li>
       <li class="nav-item">
        <%= link_to 'Order history',orders_history_index_path,class: 'nav-link',style:"color:black;" %>
    </li>
     <li> <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link',style:"color:black;" %>
    </li>
  </ul>
</div>
<!--end user dropdown-->
<!--start category dropdown-->
<div class="dropdown" style="margin-left: 10px;">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
    select category
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
   <li class="nav-item">
      <%= link_to 'All category',categories_path,class: 'nav-link',style:"color:black;" %>
  </li>
  </ul>
</div>
<!-- end category list-->
 <li class="nav-item">
    <%= link_to 'Map',maps_path,class: 'nav-link',style:"color:white;margin-left:5px;width:100px;",class:"btn btn-secondary" %>
</li>
<% end %>
<% else %>
<% end %>
<li class="nav-item">
  <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true"></a>
</li>
</ul>
</div>
</div>
</nav>

app/views/home/index.html.erb
 <style>

   .btn-grad {background-image: linear-gradient(to right, #16A085 0%, #F4D03F  51%, #16A085  100%)}
   .btn-grad {
      padding: 10px 15px;
      text-align: center;
      text-transform: uppercase;
      transition: 0.5s;
      background-size: 200% auto;
      color: white;
      box-shadow: 0 0 20px #eee;
      border-radius: 8px;
      display: block;
      text-decoration: none;
    }

    .btn-grad:hover {
      background-position: right center; /* change the direction of the change here */
      color: #fff;
      text-decoration: none;
    }
  #card
  {
  width: 353px;
  height: 235px;
   transition: 1s all;
  }
 #card:hover
  {
  width: 353px;
  height: 235px;
  border-radius: 10px;
  box-shadow: 2px 2px 5px black ;
  transition: 500ms linear;
  transform: scale(1.2);
  /*transform-origin: top;*/
  z-index: 100;
  }
</style>
<h3 style="text-align: center;font-family: cursive;">Welcome to dashboard</h3>
<div class="container">
<div class="row" >
  <% @vegetable.each do |vege|%>
  <div class="col-sm-4">
    <div class="card mb-3" style="max-width: 540px;"id="card">
      <div class="row g-0" >
        <div class="col-md-4" style="margin-top:30px;">
          <!-- <img src="..." class="img-fluid rounded-start" alt="...">-->
          <%= image_tag(vege.vegetable_img) if vege.vegetable_img.attached?%>
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title"><%= vege.name%></h5>
            <p class="card-text"><%= vege.price%> </p>
            <p class="card-text"><%= vege.category_id%> </p>
            <p class="card-text"><%= vege.description%> </p>
            <% if current_user.role =='admin'%>
            <%= link_to "Show" ,vegetable_path(vege.id) ,class:"btn btn-primary",style:"margin-right:-1px;"%>
            <%= link_to "Edit" ,edit_vegetable_path(vege.id),class:"btn btn-primary",style:"margin-left:-1px;"%>
            <%= link_to "Delete" ,vegetable_path(vege.id),method: :delete,class:"btn btn-danger"%>
            <%else%>
            <%= link_to "Add to cart" ,add_to_cart_path(cart_id: @cart_id ,id: vege.id,price: vege.price,name:vege.name,vegetable_img:vege.vegetable_img),class:"btn-grad ", method:"post"%><br>
            <i class="fa fa-star" aria-hidden="true" style="margin-left: 20px;color:#f4ec10;"></i>
            <i class="fa fa-star" aria-hidden="true" style="color:#f4ec10"></i>
            <i class="fa fa-star" aria-hidden="true"style="color:#f4ec10"></i>
            <i class="fa fa-star" aria-hidden="true"></i>
            <i class="fa fa-star" aria-hidden="true"></i>
            <%end%>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%end%>
</div>
<div class="row">
  <div class="col-sm-10"></div>
  <div class="col-sm-2">
    <%= will_paginate @vegetable, renderer: BootstrapPagination::Rails%>
  </div>
</div>

app/views/maps/index.html.erb
<h4 style="font-family:cursive;text-align: center;">Map Result </h4>

<div class="container">
	<div class="row">
		<div class="col-sm-12">
			<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3502.276271896476!2d77.37672125012006!3d28.62148088233597!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390ceff42528a613%3A0x9d28c928f1474a32!2sChetu!5e0!3m2!1sen!2sin!4v1645267763938!5m2!1sen!2sin" width="1100" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
		</div>
	</div>
</div>