config/routes.rb
Rails.application.routes.draw do
  get 'buy/index'
    namespace 'v1' do
      resources :api_tables
    end
  get 'orders/index'
  get 'orders_history/index'
  devise_for :users
  get 'home/index'
  get 'home/index'
  root to: "home#index"
  resources :vegetables
  resources :categories
  resources :maps
  resources :addresses
  resources :orders
  resources :order_histories
  resources :user_profiles
  resources :cart_items
  resources :buy
  post '/add_to_cart', to: 'vegetables#add_to_cart'
  post '/create', to: 'orders#create'
  post '/incr_quantity', to: 'vegetables#incr_quantity'
  post '/decr_quantity', to: 'vegetables#decr_quantity'
  get '/send_mail' => 'orders#send_mail'
  # resources :charges, only: [:new, :create]


end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/api_table.rb
class ApiTable < ApplicationRecord
	validates :name , presence: true
	validates :email , presence: true
	validates :password , presence: true
	validates :auth , presence: true
	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
   
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
	has_many :cart_items
	belongs_to :user
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	has_many :vegetables
	belongs_to :cart
	has_many_attached :vegetable_img
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :vegetables
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :user
	belongs_to :vegetable

   
end

app/models/order_history.rb
class OrderHistory < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  devise :database_authenticatable, :validatable, password_length: 6..128
  has_one_attached :user_img
  has_many :addresses
  has_one :cart
  has_many :cart_items
  has_many :orders

end

app/models/vegetable.rb
class Vegetable < ApplicationRecord
	belongs_to :cart_item
	has_many :orders
	has_one_attached :vegetable_img
	def self.search_by(search_term)
	where("LOWER(name) LIKE :search_term ",search_term: "%#{search_term.downcase}%")
	end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
def index
    @cart = current_user.cart_items
end

# def current_cart
# 	if session[:cart_id]
# 	@current_cart ||= CartItem.find(session[:cart_id])
# 	end
# 	if session[:cart_id].nil?
# 	@current_cart = Cart.create!
# 	session[:cart_id] = @current_cart.id
# 	end
# 	@current_cart
# end
def show
	@cart = CartItem.find_by(id: params[:id])
end

def checkout
	cart = current_user.cart
	cart_items = cart.cart_items
	total_cart_value = 0
	cart_items.each do |ci|
		total_cart_value = total_cart_value + (ci.quntity.to_i*ci.price.to_i)
	end
end

def destroy
	@cart = CartItem.find_by(id: params[:id])
	if @cart.present?
		@cart.destroy
	 	redirect_to cart_items_path
	end
end

private

def cart_params
	params.require(:CartItem).permit(:user_id ,:vegetable_id , :cart_id ,:price ,:quntity ,:vegetable_img)
end



end

app/controllers/home_controller.rb
class HomeController < ApplicationController

def index
    @vegetable = Vegetable.all.paginate(page: params[:page], per_page: 6)
  if params[:search]
    @search_term = params[:search]
    @vegetable = Vegetable.search_by(@search_term).paginate(page: params[:page], per_page: 6)
  end
end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController

	def index
	end
end

app/helpers/address_helper.rb
module AddressHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/helpers/vegetables_helper.rb
module VegetablesHelper
end

app/views/cart_items/index.html.erb
<style>

 .btn-grad {background-image: linear-gradient(to right, #314755 0%, #26a0da  51%, #314755  100%)}
 .btn-grad {
    padding: 10px 15px;
    text-align: center;
    text-transform: uppercase;
    transition: 0.5s;
    background-size: 200% auto;
    color: white;
    box-shadow: 0 0 5px #eee;
    border-radius: 10px;
    display: block;
     text-decoration: none;
  }
  .btn-grad:hover {
    background-position: right center; /* change the direction of the change here */
    color: #fff;
    text-decoration: none;
  }
    #card
  {
  transition: 1s all;
  }
 #card:hover
  {
  border-radius: 10px;
  box-shadow: 0px 0px 5px 1px black ;
  transition: 500ms linear;
  z-index: 1000;
  }

 #all_T_amount
 {
  font-family:cursive;
  position:absolute;
  top: 70px;
  left: 800px;
 }
  #all_buy_btn
 {
  font-family:cursive;
  position:absolute;
  top: 60px;
  left: 1140px;
 }

  #all_T_amount:hover
 {
  color: darkgreen;
  font-family: bold;
  font-family:cursive;
  position: fixed;
  top: 70px;
  left: 850px;
  z-index: 1;
 }
</style>

 <div id="all_T_amount">
  <span>Total Cart Amount : </span>
    <span>
      <%=@cart.map(&:price).map(&:to_i).sum%>
    </span>
    <span style="margin-left:10px;">Total cart Item :
      <span><%=@cart.map(&:id).count%></span>
    </span>
  </div>
   <% @cart.each_with_index do |cart, index|%>
   <span id = all_buy_btn>
    <%=link_to "Buy now" ,orders_path(bunch_buy: true , ids: @cart.map(&:id),user_id: @user_id ,id: Vegetable.find(cart.vegetable_id)), class: "btn-grad"%></span> &nbsp;&nbsp;&nbsp;
<%end%>
<h2 style="font-family:cursive;text-align:center">Cart Data</h2>
<div class="container">
  <iv class="row">
    <% @cart.each_with_index do |cart, index|%>
    <% vegetable = Vegetable.find(cart.vegetable_id)%>
    <div class="col-sm-12">
      <div class="card mb-3">
        <div class="row g-0"id="card">
          <div class="col-md-4" style="margin-top:50px;padding-left: 100px;">
            <!-- <img src="..." class="img-fluid rounded-start" alt="...">-->
            <%#byebug%>
            <%= image_tag(vegetable.vegetable_img) if cart.vegetable_id.present?%>
          </div>
          <div class="col-md-8">
            <div class="card-body"style="margin-left: 100px;">
              <p class="card-title"><b>Name : </b><%=Vegetable.find(cart.vegetable_id).name%></p>
              <p class="card-text" ><b>Price : </b><span id="price_<%= cart.id %>"><%= cart.price%></span> </p>
              <b>User id : </b> <%=cart.vegetable_id%>
             <b>Vegetable  id : </b> <%=cart.vegetable_id%>
              <p class="card-text" ><b>Quantity : </b><span id= "quantity_<%=cart.id %>"><%=cart.quntity.to_i%></span></p>
               <%#byebug%>
              <%=link_to "Buy now",cart_item_path(user_id: current_user.id,id:cart.id,vegetable_id: Vegetable.find(cart.vegetable_id).id,vegetable_img:cart.vegetable_img), class: "btn btn-primary"%><!--method="post"-->
            <%#=link_to "buy now",cart_item_path(user_id: @user_id ,id: cart.id), class: "btn btn-primary"%>
              <%=link_to "Remove" ,cart_item_path(cart.id),method: :delete ,data: {confirm:"Are You Soure ?"} ,class: "btn btn-danger"%>
              <br></br>
              <input type="button" id= "<%= cart.id %>" value="-" class="decriment" />
              <input type="text" name="quantity" value="<%= cart.quntity ? cart.quntity : "1" %>"   size="1" id="number_<%=cart.id %>" style="text-align:center;" />
              <input type="button" id= "<%= cart.id %>" value="+" class="increment" />
             <P style="margin-top:10px;margin-left: 210px;">Total Amount : </P><p class="card-text"  id="total_<%=cart.id%>" style="margin-left: 340px;margin-top: -40px;" ><%=(cart.quntity.to_i*cart.price.to_i)%></p>
            </div>
          </div>

        </div>

      </div>
    </div>
    <%end%>
  </div>
</div>
<script type="text/javascript">
  $(".increment").on("click", function(){
    id = $(this).attr("id")
    var text_value;
    text_value = document.getElementById("number_"+id).value
   text_value++
     // document.getElementById("number_"+id).val = text_value
      // document.getElementById("total_"+id).innerHTML = text_value
    data_text = document.getElementById("number_"+id).value =text_value
    id = this.id
     $.ajax({
        type: "POST",
        url: "/incr_quantity",
        dataType: "json",
        data: {
            value: data_text,
            id: id// < note use of 'this' here
        },
        success: function(data) {
            alert('Product add Successfully');
            document.getElementById("quantity_"+id).innerHTML = text_value
            total_price = document.getElementById("price_"+id).innerHTML * text_value
            document.getElementById("total_"+id).innerHTML = total_price

        },
        error: function(data) {
            alert('error');
        }
    });
});

  $(".decriment").on("click", function(){
    id = $(this).attr("id")
    var text_value;
    text_value = document.getElementById("number_"+id).value
    text_value--
    document.getElementById("number_"+id).val =text_value
    document.getElementById("number_"+id).value =text_value
    id = this.id
     $.ajax({
        type: "POST",
        url: "/decr_quantity",
        dataType: "json",
        data: {
            value: data_text,
            id: id// < note use of 'this' here
        },
        success: function(data) {
            alert('Product decreased');
             document.getElementById("quantity_"+id).innerHTML = text_value
             total_price = document.getElementById("price_"+id).innerHTML * text_value
            document.getElementById("total_"+id).innerHTML = total_price
        },
        error: function(data) {
            alert('error');
        }
    });
});
</script>

app/views/cart_items/show.html.erb
<style type="text/css">
  .bclass
  {
    font-family: serif;
  }
</style>
<div class="container px-4 m-2">
<div class="row gx-5">
  <div class="col">
     <div class="p-3 border bg-light">
        <%= image_tag(Vegetable.find(@cart.vegetable_id).vegetable_img,style:"margin-left:100px;height:180px;width:300px;") if @cart.present?%>
     </div>
  </div>
  <div class="col">
     <div class="p-3 border bg-light">
        <b class="bclass">user Id : </b> <%=@cart.user_id%><br>
        <b class="bclass">vegetable Id : </b> <%=@cart.vegetable_id%><br>
        <b class="bclass">Cart Id: </b> <%=@cart.cart_id%><br>
        <b class="bclass">Quantity  : </b><%=@cart.quntity%><br>
        <b class="bclass">price : </b> <%=@cart.price.to_i*@cart.quntity.to_i%><br>
        <%#=link_to "Buy now",cart_item_path(user_id: current_user.id ,vegetable_id: Vegetable.find(cart.vegetable_id).id),
           method: 'post', class: "btn btn-primary"%>
           <%#byebug%>
        <p class="confirm"><%=link_to "CONFIRM",orders_path(user_id: current_user.id , vegetable_id: params[:vegetable_id], address_id: params[:id],cartitems_id: params[:ids], bunch_buy: params[:buch_buy]),class:"btn btn-warning",style:"margin-left:250px;width:200px;color:white;font-family:bold;",method:"post"%>
        </p>
     </div>
  </div>
</div>
</div>
<script type="text/javascript">
$(".confirm").on("click", function(){
alert("product ordered Successfully")
});
</script>