config/routes.rb
Rails.application.routes.draw do
  get 'buy/index'
    namespace 'v1' do
      resources :api_tables
    end
  get 'orders/index'
  get 'orders_history/index'
  devise_for :users
  get 'home/index'
  get 'home/index'
  root to: "home#index"
  resources :vegetables
  resources :categories
  resources :maps
  resources :addresses
  resources :orders
  resources :order_histories
  resources :user_profiles
  resources :cart_items
  resources :buy
  post '/add_to_cart', to: 'vegetables#add_to_cart'
  post '/create', to: 'orders#create'
  post '/incr_quantity', to: 'vegetables#incr_quantity'
  post '/decr_quantity', to: 'vegetables#decr_quantity'
  get '/send_mail' => 'orders#send_mail'
  # resources :charges, only: [:new, :create]


end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/api_table.rb
class ApiTable < ApplicationRecord
	validates :name , presence: true
	validates :email , presence: true
	validates :password , presence: true
	validates :auth , presence: true
	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
   
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
	has_many :cart_items
	belongs_to :user
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	has_many :vegetables
	belongs_to :cart
	has_many_attached :vegetable_img
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :vegetables
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :user
	belongs_to :vegetable

   
end

app/models/order_history.rb
class OrderHistory < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  devise :database_authenticatable, :validatable, password_length: 6..128
  has_one_attached :user_img
  has_many :addresses
  has_one :cart
  has_many :cart_items
  has_many :orders

end

app/models/vegetable.rb
class Vegetable < ApplicationRecord
	belongs_to :cart_item
	has_many :orders
	has_one_attached :vegetable_img
	def self.search_by(search_term)
	where("LOWER(name) LIKE :search_term ",search_term: "%#{search_term.downcase}%")
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :find_category,only: [:edit, :show, :update, :destroy]
	def new
		@category = Category.new
	end

	def index
		@category = Category.all
	end

	def create
		@category = Category.new(parmas_category)
		if @category.save
			redirect_to categories_path
		else
			render "new"
		end
	end

	def show
	end

	def edit
	end

	def update
		if @category.update(parmas_category)
			redirect_to categories_path
		else
			render "edit"
		end
	end

	def destroy
		if @category.destroy
			redirect_to categories_path
	    end
	end

	private

	def parmas_category
		params.require(:category).permit(:name)
	end

	def find_category
		@category = Category.find_by(id: params[:id])
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

def index
    @vegetable = Vegetable.all.paginate(page: params[:page], per_page: 6)
  if params[:search]
    @search_term = params[:search]
    @vegetable = Vegetable.search_by(@search_term).paginate(page: params[:page], per_page: 6)
  end
end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController

	def index
	end
end

app/helpers/address_helper.rb
module AddressHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/helpers/vegetables_helper.rb
module VegetablesHelper
end

app/views/categories/edit.html.erb
<div class="container">
<div class="row">
  <div class="col-sm-3"></div>
  <div class="col-sm-4" style="margin: 10px;">
    <h3 style="font-family:cursive;text-align: center;">Add new Category </h3>
    <%=form_for @category do |f|%>
      <%=f.label :name%>
      <%=f.text_field :name,class:"form-control"%>
       <%=f.submit "Update",class:"btn btn-primary",style:"margin-top:10px;"%> 
    <%end%>
  </div>
</div>
</div>

app/views/categories/index.html.erb
<div class="container">
<div class="row" style="margin-top:10px;">
<% @category.each do |cat|%>
   <div class="col-sm-4" style="margin-top:10px;">
    <div class="card" style="width: 18rem;">
     <div class="card-body">
      <h5 class="card-title" style="text-align:center;font-family:cursive;"><%=cat.name%></h5>
      <% if current_user.role == "admin"%>
        <%= link_to "Show" ,category_path(cat.id),class:"btn btn-info"%>
          <%= link_to "Edit " ,edit_category_path(cat.id),class:"btn btn-info"%>
            <%= link_to "Destroy" ,category_path(cat.id),method: :delete,class:"btn btn-danger"%>
            <%else%>
            <%= link_to "Show" ,category_path(cat.id),class:"btn btn-info",style:"width:250px;"%>
            <%end%>
    </div>
  </div>
</div>
<%end%>
</div>
</div>

app/views/categories/new.html.erb
<div class="container">
<div class="row">
  <div class="col-sm-3"></div>
  <div class="col-sm-4" style="margin: 10px;">
    <h3 style="font-family:cursive;text-align: center;">Add new Category </h3>
    <%=form_for @category do |f|%>
      <%=f.label :name%>
      <%=f.text_field :name,class:"form-control"%>
       <%=f.submit "add category",class:"btn btn-primary",style:"margin-top:10px;"%>
    <%end%>
  </div>
</div>
</div>

app/views/categories/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-3"></div>
     <div class="col-sm-4">
      <div class="card" style="width: 18rem;">
       <div class="card-body">
        <h5 class="card-title"><%=@category.name%></h5>
          <%= link_to "Back" ,categories_path,class:"btn btn-warning"%>
      </div>
    </div>
</div>
</div>
</div>